# Generated by Django 5.2.16 on 2026-07-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_comment_marked_right_at_comment_marked_right_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='marked_right_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
