# Generated by Django 5.2.16 on 2026-07-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_comment_marked_right_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["order"]},
        ),
    ]
