# Generated by Django 5.2.16 on 2026-07-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_chapter_options_alter_lesson_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="learningresource",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="complete_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm hoàn thành"
            ),
        ),
    ]
