# Generated by Django 5.2.16 on 2026-07-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_chapter_is_active_alter_comment_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm công khai cho học sinh"
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm công khai cho học sinh"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm công khai cho học sinh"
            ),
        ),
    ]
