# Generated by Django 5.2.16 on 2026-08-08 10:39

from django.db import migrations, models


def set_rag_status(apps, schema_editor):
    LearningResource = apps.get_model("courses", "LearningResource")
    LearningResource.objects.filter(is_rag_indexed=True).update(rag_status="INDEXED")


def restore_is_rag_indexed(apps, schema_editor):
    LearningResource = apps.get_model("courses", "LearningResource")
    LearningResource.objects.filter(rag_status="INDEXED").update(is_rag_indexed=True)


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_publish_existing_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="rag_error",
            field=models.TextField(blank=True, null=True, verbose_name="Lý do nạp lỗi"),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="rag_indexed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm nạp xong"
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="rag_progress",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Số chunk đã nạp"
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="rag_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ nạp"),
                    ("PROCESSING", "Đang nạp"),
                    ("INDEXED", "Đã nạp"),
                    ("FAILED", "Nạp lỗi"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Trạng thái RAG",
            ),
        ),
        migrations.RunPython(set_rag_status, restore_is_rag_indexed),
        migrations.RemoveField(
            model_name="learningresource",
            name="is_rag_indexed",
        ),
    ]
