# Generated by Django 5.2.16 on 2026-09-01 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_alter_grade_options_alter_material_options_and_more"),
        ("courses", "0008_remove_learningresource_is_rag_indexed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={
                "ordering": ["order"],
                "verbose_name": "Chương",
                "verbose_name_plural": "Chương",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Bình luận", "verbose_name_plural": "Bình luận"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Khóa học", "verbose_name_plural": "Khóa học"},
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "Lượt ghi danh",
                "verbose_name_plural": "Lượt ghi danh",
            },
        ),
        migrations.AlterModelOptions(
            name="learningresource",
            options={
                "verbose_name": "Tài nguyên bài học",
                "verbose_name_plural": "Tài nguyên bài học",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["order"],
                "verbose_name": "Bài học",
                "verbose_name_plural": "Bài học",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonprogress",
            options={
                "verbose_name": "Tiến độ học bài",
                "verbose_name_plural": "Tiến độ học bài",
            },
        ),
        migrations.AlterField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="courses.course",
                verbose_name="Khóa học",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="Nội dung bình luận"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người viết",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_right",
            field=models.BooleanField(
                default=False, verbose_name="Được đánh dấu là đúng"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="courses.lesson",
                verbose_name="Bài học",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="marked_right_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm đánh dấu đúng"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="marked_right_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_right_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người đánh dấu đúng",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="courses.comment",
                verbose_name="Bình luận cha",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="course",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="academics.grade",
                verbose_name="Khối lớp",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                related_name="courses",
                through="courses.Enrollment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Học sinh theo học",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="learning_courses",
                to="academics.subject",
                verbose_name="Môn học",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="tutor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gia sư phụ trách",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.course",
                verbose_name="Khóa học",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Học sinh",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
        migrations.AlterField(
            model_name="learningresource",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="learningresource",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="learningresource",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="courses.lesson",
                verbose_name="Bài học",
            ),
        ),
        migrations.AlterField(
            model_name="learningresource",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
        migrations.AlterField(
            model_name="learningresource",
            name="video_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Đường dẫn video"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.chapter",
                verbose_name="Chương",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="students",
            field=models.ManyToManyField(
                related_name="lessons",
                through="courses.LessonProgress",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Học sinh đã học",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.lesson",
                verbose_name="Bài học",
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Học sinh",
            ),
        ),
    ]
