# Generated by Django 5.2.16 on 2026-08-26 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0002_initial"),
        ("courses", "0008_remove_learningresource_is_rag_indexed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Câu hỏi của học sinh")),
                ("answer", models.TextField(verbose_name="Câu trả lời của trợ lý AI")),
                (
                    "sources",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Nguồn tài liệu"
                    ),
                ),
                (
                    "is_grounded",
                    models.BooleanField(
                        verbose_name="Trả lời dựa trên tài liệu khóa học"
                    ),
                ),
                ("asked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["student", "course"],
                        name="AI_conversa_student_b42da7_idx",
                    )
                ],
            },
        ),
    ]
