# Generated by Django 5.2.16 on 2026-09-01 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0003_conversation"),
        ("assignments", "0013_alter_answer_options_alter_assignment_options_and_more"),
        ("courses", "0009_alter_chapter_options_alter_comment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "ordering": ["-id"],
                "verbose_name": "Lượt hỏi trợ lý AI",
                "verbose_name_plural": "Lượt hỏi trợ lý AI",
            },
        ),
        migrations.AlterModelOptions(
            name="report",
            options={
                "verbose_name": "Báo cáo câu hỏi",
                "verbose_name_plural": "Báo cáo câu hỏi",
            },
        ),
        migrations.AlterField(
            model_name="conversation",
            name="asked_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm hỏi"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="Khóa học",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.lesson",
                verbose_name="Bài học",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Học sinh",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="note",
            field=models.TextField(verbose_name="Nội dung báo cáo"),
        ),
        migrations.AlterField(
            model_name="report",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.question",
                verbose_name="Câu hỏi bị báo lỗi",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reported_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Thời điểm báo cáo"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người báo cáo",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("REPORTED", "Đã báo cáo"),
                    ("REVIEWING", "Đang xem xét"),
                    ("SOLVED", "Đã xử lý"),
                ],
                default="REPORTED",
                max_length=255,
                verbose_name="Trạng thái xử lý",
            ),
        ),
    ]
