# Generated by Django 5.2.16 on 2026-09-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0004_alter_conversation_options_alter_report_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
