# Generated by Django 5.2.16 on 2026-08-08 10:39

import academics.models
import cloudinary.models
from django.db import migrations, models


def set_rag_status(apps, schema_editor):
    Material = apps.get_model("academics", "Material")
    Material.objects.filter(is_rag_indexed=True).update(rag_status="INDEXED")


def restore_is_rag_indexed(apps, schema_editor):
    Material = apps.get_model("academics", "Material")
    Material.objects.filter(rag_status="INDEXED").update(is_rag_indexed=True)


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_grade_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={},
        ),
        migrations.AddField(
            model_name="material",
            name="local_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=academics.models.material_local_path,
                verbose_name="Tệp lưu cục bộ",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="rag_error",
            field=models.TextField(blank=True, null=True, verbose_name="Lý do nạp lỗi"),
        ),
        migrations.AddField(
            model_name="material",
            name="rag_indexed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm nạp xong"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="rag_progress",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Số chunk đã nạp"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="rag_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ nạp"),
                    ("PROCESSING", "Đang nạp"),
                    ("INDEXED", "Đã nạp"),
                    ("FAILED", "Nạp lỗi"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Trạng thái RAG",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="file_url",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tệp trên Cloudinary",
            ),
        ),
        migrations.RunPython(set_rag_status, restore_is_rag_indexed),
        migrations.RemoveField(
            model_name="material",
            name="is_rag_indexed",
        ),
    ]
