# Generated by Django 5.2.16 on 2026-09-01 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0004_alter_subject_options_remove_material_is_rag_indexed_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={
                "ordering": ["number"],
                "verbose_name": "Khối lớp",
                "verbose_name_plural": "Khối lớp",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"verbose_name": "Tài liệu", "verbose_name_plural": "Tài liệu"},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name": "Môn học", "verbose_name_plural": "Môn học"},
        ),
        migrations.AlterField(
            model_name="grade",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="material",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="academics.grade",
                verbose_name="Khối lớp",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên tài liệu"),
        ),
        migrations.AlterField(
            model_name="material",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="academics.subject",
                verbose_name="Môn học",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
    ]
