# Generated by Django 5.2.16 on 2026-07-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="time_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Thời gian làm bài (phút)"
            ),
        ),
    ]
