# Generated by Django 5.2.16 on 2026-07-27 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_assignment_time_limit_minutes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Thứ tự câu hỏi"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="assignments.question",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["assignment", "order"], name="assignments_assignm_685e7b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("assignment", "order"), name="unique_assignment_question_order"
            ),
        ),
    ]
