# Generated by Django 5.2.16 on 2026-07-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_question_options_question_order_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="submission",
            name="unique_assignment_student",
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="point",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
