# Generated by Django 5.2.16 on 2026-07-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_remove_submission_unique_assignment_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
