# Generated by Django 5.2.16 on 2026-07-29 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_alter_submission_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["-started_at", "-id"]},
        ),
        migrations.AddField(
            model_name="submission",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm bắt đầu làm bài"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm nộp bài"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["assignment", "student"], name="assignments_assignm_6c6845_idx"
            ),
        ),
    ]
