# Generated by Django 5.2.16 on 2026-07-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0006_alter_submission_options_submission_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm công khai cho học sinh"
            ),
        ),
    ]
