# Generated by Django 5.2.16 on 2026-08-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0007_assignment_published_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["-id", "-started_at"]},
        ),
    ]
