# Generated by Django 5.2.16 on 2026-08-26 12:04

from django.db import migrations, models


def remove_duplicate_student_answers(apps, schema_editor):
    StudentAnswer = apps.get_model("assignments", "StudentAnswer")

    rows_by_question = {}
    for row in StudentAnswer.objects.all():
        key = (row.submission_id, row.question_id)
        rows_by_question.setdefault(key, []).append(row)

    doomed_ids = []
    for rows in rows_by_question.values():
        if len(rows) < 2:
            continue
        rows.sort(key=lambda row: (row.point is not None, row.id), reverse=True)
        doomed_ids.extend(row.id for row in rows[1:])

    if doomed_ids:
        StudentAnswer.objects.filter(id__in=doomed_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0008_alter_submission_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["-id"]},
        ),
        migrations.RunPython(
            remove_duplicate_student_answers, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="studentanswer",
            constraint=models.UniqueConstraint(
                fields=("submission", "question"), name="unique_submission_question"
            ),
        ),
    ]
