# Generated by Django 5.2.16 on 2026-08-27 06:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0009_alter_submission_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="point",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.25"),
                max_digits=4,
                verbose_name="Điểm của câu hỏi",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
