# Generated by Django 5.2.16 on 2026-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0011_split_points_for_existing_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="point",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Điểm của câu hỏi",
            ),
        ),
    ]
