# Generated by Django 5.2.16 on 2026-09-01 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0012_alter_question_point"),
        ("courses", "0009_alter_chapter_options_alter_comment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "verbose_name": "Phương án trả lời",
                "verbose_name_plural": "Phương án trả lời",
            },
        ),
        migrations.AlterModelOptions(
            name="assignment",
            options={"verbose_name": "Bài tập", "verbose_name_plural": "Bài tập"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["order"],
                "verbose_name": "Câu hỏi",
                "verbose_name_plural": "Câu hỏi",
            },
        ),
        migrations.AlterModelOptions(
            name="studentanswer",
            options={
                "verbose_name": "Câu trả lời của học sinh",
                "verbose_name_plural": "Câu trả lời của học sinh",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ["-id"],
                "verbose_name": "Bài nộp",
                "verbose_name_plural": "Bài nộp",
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(verbose_name="Là phương án đúng"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="assignments.question",
                verbose_name="Câu hỏi",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="chapter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.chapter",
                verbose_name="Chương",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(verbose_name="Hạn nộp"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="students",
            field=models.ManyToManyField(
                related_name="assignments",
                through="assignments.Submission",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Học sinh được giao",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assignments.assignment",
                verbose_name="Bài tập",
            ),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assignments.answer",
                verbose_name="Phương án đã chọn",
            ),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="answer_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Câu trả lời tự luận"
            ),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="point",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Điểm câu này",
            ),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="assignments.question",
                verbose_name="Câu hỏi",
            ),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stu_answers",
                to="assignments.submission",
                verbose_name="Bài nộp",
            ),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="tutor_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nhận xét của gia sư"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="assignments.assignment",
                verbose_name="Bài tập",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, null=True, verbose_name="Điểm bài làm"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Học sinh",
            ),
        ),
    ]
