# Generated by Django 5.2.16 on 2026-09-04 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0013_alter_answer_options_alter_assignment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentanswer",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="assignments.answer",
                verbose_name="Phương án đã chọn",
            ),
        ),
    ]
