# Generated by Django 5.2.16 on 2026-09-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0014_alter_studentanswer_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Là phương án đúng"),
        ),
    ]
