# Generated by Django 5.2.16 on 2026-09-01 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_alter_grade_options_alter_material_options_and_more"),
        ("accounts", "0002_alter_studentprofile_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "verbose_name": "Hồ sơ học sinh",
                "verbose_name_plural": "Hồ sơ học sinh",
            },
        ),
        migrations.AlterModelOptions(
            name="tutorprofile",
            options={
                "verbose_name": "Hồ sơ gia sư",
                "verbose_name_plural": "Hồ sơ gia sư",
            },
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="academic_level",
            field=models.CharField(
                choices=[
                    ("POOR", "Yếu"),
                    ("AVERAGE", "Trung bình"),
                    ("GOOD", "Khá"),
                    ("EXCELLENT", "Giỏi"),
                ],
                default="AVERAGE",
                max_length=20,
                verbose_name="Học lực",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="grade_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.grade",
                verbose_name="Khối lớp",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tài khoản",
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm tạo"),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Thời điểm cập nhật"
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tài khoản",
            ),
        ),
    ]
