# Generated by Django 5.2.16 on 2026-09-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_studentprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorprofile",
            name="experience_years",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Số năm kinh nghiệm"
            ),
        ),
    ]
